repos:


  # Native Black for .py files
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        name: Black for Python files
        args: ["--line-length=120", "--target-version=py310", "--check", "--diff"]
        files: ^src/.*\.py$

  # Native Flake8 for .py files
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: Flake8 for Python files
        args: ["--max-line-length=120", "--ignore=F403,F405,E203,W503", "--extend-ignore=E501,F821,E231,E241,E202"]
        files: ^src/.*\.py$

  # Black Code Formatter - .ipynb files
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
      - id: nbqa-black
        name: nbqa-black for raw_to_silver
        args: ["--line-length=120", "--target-version=py310", "--check", "--diff"]
        additional_dependencies: ["black==23.3.0"]
        files: ^src/udp_etl_framework/raw_to_silver/.*\.ipynb$

      - id: nbqa-black
        name: nbqa-black for silver_to_gold
        args: ["--line-length=120", "--target-version=py310", "--check", "--diff"]
        additional_dependencies: ["black==23.3.0"]
        files: ^src/udp_etl_framework/silver_to_gold/.*\.ipynb$

      - id: nbqa-black
        name: nbqa-black for common
        args: ["--line-length=120", "--target-version=py310", "--check", "--diff"]
        additional_dependencies: ["black==23.3.0"]
        files: ^src/udp_etl_framework/common/.*\.ipynb$

      - id: nbqa-black
        name: nbqa-black for artifact
        args: ["--line-length=120", "--target-version=py310", "--check", "--diff"]
        additional_dependencies: ["black==23.3.0"]
        files: ^src/udp_etl_framework/artifact/.*\.ipynb$

      - id: nbqa-black
        name: nbqa-black for utils
        args: ["--line-length=120", "--target-version=py310", "--check", "--diff"]
        additional_dependencies: ["black==23.3.0"]
        files: ^src/udp_etl_framework/utils/.*\.ipynb$


  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.1
    hooks:
      # raw_to_silver
      - id: nbqa-flake8
        name: Flake8 Notebook Linter - raw_to_silver
        description: "Python linting for Jupyter notebooks with flake8"
        args: ["--max-line-length=120", "--ignore=F403,F405,E203,W503", "--extend-ignore=E501,F821,E231,E241,E202"]
        files: ^src/udp_etl_framework/raw_to_silver/.*\.ipynb$
        additional_dependencies: [flake8==6.0.0]

      # silver_to_gold
      - id: nbqa-flake8
        name: Flake8 Notebook Linter - silver_to_gold
        description: "Python linting for Jupyter notebooks with flake8"
        args: ["--max-line-length=120", "--ignore=F403,F405,E203,W503", "--extend-ignore=E501,F821,E231,E241,E202"]
        files: ^src/udp_etl_framework/silver_to_gold/.*\.ipynb$
        additional_dependencies: [flake8==6.0.0]

      # common
      - id: nbqa-flake8
        name: Flake8 Notebook Linter - common
        description: "Python linting for Jupyter notebooks with flake8"
        args: ["--max-line-length=120", "--ignore=F403,F405,E203,W503", "--extend-ignore=E501,F821,E231,E241,E202"]
        files: ^src/udp_etl_framework/common/.*\.ipynb$
        additional_dependencies: [flake8==6.0.0]

      # artifact
      - id: nbqa-flake8
        name: Flake8 Notebook Linter - artifact
        description: "Python linting for Jupyter notebooks with flake8"
        args: ["--max-line-length=120", "--ignore=F403,F405,E203,W503", "--extend-ignore=E501,F821,E231,E241,E202"]
        files: ^src/udp_etl_framework/artifact/.*\.ipynb$
        additional_dependencies: [flake8==6.0.0]

      # utils
      - id: nbqa-flake8
        name: Flake8 Notebook Linter - utils
        description: "Python linting for Jupyter notebooks with flake8"
        args: ["--max-line-length=120", "--ignore=F403,F405,E203,W503", "--extend-ignore=E501,F821,E231,E241,E202"]
        files: ^src/udp_etl_framework/utils/.*\.ipynb$
        additional_dependencies: [flake8==6.0.0]


 # Local hooks
  - repo: local
    hooks:
      - id: large-file-check
        name: Large File Check
        entry: python tests/large_file_check.py
        language: python
        types: [file]
        files: ^src/.*\.(py|ipynb)$